test:
  message: hello
#Features
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feature:
    registration:
        enabled: true
    signin:
        enabled: true
    askquestion:
        enabled: true
    answerquestion:
        enabled: true
