test:
  message: hello
#Features
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feature:
  registration:
    enabled: true
  askquestion:
    enabled: true
